### ISSUE TITLE
Directly use libVLC

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/PlayLiveATC#4]
**Current Situation / Problem**
Currently, an external VLC player is spawned, which we have little control over. (See #3 for a suggestion to use the RC interface...but that is still relatively little control.)

**Suggested Solution**
Directly use libVLC so that there would be no need any longer to spawn a separate process. Instead, VLC would run directly in X-Plane/SwitchLiveATC...which would become **Play**LiveATC!

**Benefits**
~~No dependency on a VLC installation.~~ With an existing VLC installation plugin installation will still use it, but theoretically I could provide a minimal VLC setup right with the plugin and no need to download VLC additionally. For Windows, this includes VLC.dll and VLCCore.dll plus a selected set of plugins for HTTP stream access and MP4 playback.

Much more direct control

**VLC Documentation entry points**
    - [Developers' doc links](https://www.videolan.org/developers/vlc.html)
    - [Wiki](https://wiki.videolan.org)
    - [libVLC documentation](https://wiki.videolan.org/LibVLC/)
    - [libVLC Tutorial (very brief)](https://wiki.videolan.org/LibVLC_Tutorial/)
    - [libvlcpp as a c++ wrapper](https://code.videolan.org/videolan/libvlcpp)

**Downloads**
The SDK is included in the 7z packages:
- For Windows, the SDK is only included in the 7z archives from [here](https://download.videolan.org/vlc/last/win64/)
- MacOS: Just the [normal download](https://download.videolan.org/vlc/last/macosx/)

**Remaining Todos**
- [x] Remove now superfluous option for VLC command line parameters
- [ ] Volume control
    - [x] Correctly mute/unmute if COM1/2 are muted (standard XP11 Cirrus TheJet offers this in the cockpit) instead of stopping/restarting
    - [x] Offer a config option for volume (Windows required to set the volume, otherwise it was muted.)
    - [ ] Offer menu plus command (for keyboard/button binding) for volume control
- [x] Windows specific:
    - [x] Fix crash on stop / shutdown
    - [x] ~~Try to fix setting the plugin path via `VLC_PLUGIN_PATH`. Has currently no effect. Currently only works if VLC plugins are installed alongside PlayLiveATC.~~ Doesn‘t work. And other forum entries on the internet say the same. So this will not work. Instead, with the VLC installation in the PATH the plugin finds all VLC DLLs and from there also the plugins.
    - [x] Alternatively, provide a setup, which includes VLC DLLs plus the minimal required plugins as a simple drop-in installation package, which however will be significantly larger than just the core plugin itself.

**Comment by dmstumpf** [comment]
Currently seeing an error during plugin init under Windows:

`Loaded: D:\X-Plane 11/Resources/plugins/PlayLiveATC/64/win.xpl (TwinFan.plugin.PlayLiveATC).`

`PlayLiveATC 02-Jun 18:50:06Z
WARN  Src\PlayLiveATC.cpp:293/XPluginEnable: BETA limited to 01-Jul-2019`

`PlayLiveATC 02-Jun 18:50:06Z
WARN  Src\PlayLiveATC.cpp:295/XPluginEnable: DEBUG BUILD with additional run-time checks and no optimizations`

`PlayLiveATC 02-Jun 18:50:06Z
ERROR Src\PLACOMChannel.cpp:154/InitVLC: Could not init VLC: Wrapping a NULL instance`

Not sure if this is due to my build environment, a change I made to PLACOMChannel.cpp to work around a setenv issue (setenv is undefined in VS 2017), or a legitimate issue with the libVLC integration.

The plugin seems to work as far as the interface goes, but it reports VLC not initialized in the in-game settings screen.

**Comment by TwinFan** [comment]
This version ist not yet ready for Windows, don’t try.
